import {Certificate} from "../models/Certificate";

export const LEVELS: Certificate[] = [
  {programName: 'AYO', level: 'AYO', theme: 'GENERAL', rank: 'AYO', rating: 1},
  {programName: 'AYO', level: 'A1.1', theme: 'SCOTLAND', rank: 'EXPLORER', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'A1.2', theme: 'SOUTH AFRICA', rank: 'EXPLORER', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'A1.3', theme: 'IRELAND', rank: 'SEEKER', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'A1.4', theme: 'ZAMBIA', rank: 'SEEKER', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'A2.1', theme: 'AUSTRALIA', rank: 'CONNECTOR', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'A2.2', theme: 'NEW ZEALAND', rank: 'CONNECTOR', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'A2.3', theme: 'CAMEROON', rank: 'CHALLENGER', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'A2.4', theme: 'CANADA', rank: 'CHALLENGER', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'B1.1', theme: 'SWEDEN', rank: 'VOYAGER', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'B1.2', theme: 'KENYA', rank: 'VOYAGER', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'B1.3', theme: 'USA', rank: 'SIMBA', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'B1.4', theme: 'ENGLAND', rank: 'SIMBA', rating: 1, language: 'INGLES'},
  {programName: 'AYO', level: 'A1.1', theme: 'FRANCE', rank: 'EXPLORATEURS', rating: 1, language: 'FRANCES'},
  {programName: 'AYO', level: 'A1.2', theme: 'BELGIQUE', rank: 'EXPLORATEURS', rating: 2, language: 'FRANCES'},
  {programName: 'AYO', level: 'A1.3', theme: 'SUISSE', rank: 'CHERCHEURS', rating: 3, language: 'FRANCES'},
  {programName: 'AYO', level: 'A1.4', theme: 'LUXEMBOURG', rank: 'CHERCHEURS', rating: 4, language: 'FRANCES'},
  {programName: 'AYO', level: 'A2.1', theme: 'MAROC', rank: 'CONNECTEURS', rating: 5, language: 'FRANCES'},
  {programName: 'AYO', level: 'A2.2', theme: 'TUNISIE', rank: 'CONNECTEURS', rating: 6, language: 'FRANCES'},
  {programName: 'AYO', level: 'A2.3', theme: 'SÉNÉGAL', rank: 'DÉBROUILLEURS', rating: 7, language: 'FRANCES'},
  {programName: 'AYO', level: 'A2.4', theme: "CÔTE-D-IVOIRE", rank: 'DÉBROUILLEURS', rating: 8, language: 'FRANCES'},
  {programName: 'AYO', level: 'B1.1', theme: 'CAMEROUN', rank: 'VOYAGEUR', rating: 9, language: 'FRANCES'},
  {programName: 'AYO', level: 'B1.2', theme: 'RD-CONGO', rank: 'VOYAGEUR', rating: 10, language: 'FRANCES'},
  {programName: 'AYO', level: 'B1.3', theme: 'FRANCE', rank: 'LYON', rating: 11, language: 'FRANCES'},
  {programName: 'AYO', level: 'B1.4', theme: 'FRANCE', rank: 'LYON', rating: 12, language: 'FRANCES'},
  {programName: 'AYO', level: 'AYO', theme: 'GENERAL', rank: 'AYO', rating: 13, language: 'FRANCES'}
];
